/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */

#line 5 "prj_test1.c"
void __globinit_prj_test1(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 202 "../bin/../include/crest.h"
extern void __CrestInt(int *x )  __attribute__((__crest_skip__)) ;
#line 363 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 5 "prj_test1.c"
int main(void) 
{ int x ;
  int __retres2 ;

  {
  __globinit_prj_test1();
  __CrestCall(1, 1);
#line 7
  __CrestInt(& x);
  {
  __CrestLoad(4, (unsigned long )(& x), (long long )x);
  __CrestLoad(3, (unsigned long )0, (long long )10);
  __CrestApply2(2, 16, (long long )(x < 10));
#line 9
  if (x < 10) {
    __CrestBranch(5, 3, 1);
#line 10
    printf((char const   * __restrict  )"GOAL\n");
    __CrestClearStack(7);
  } else {
    __CrestBranch(6, 4, 0);
#line 12
    printf((char const   * __restrict  )"GOAL1\n");
    __CrestClearStack(8);
  }
  }
  __CrestLoad(9, (unsigned long )0, (long long )0);
  __CrestStore(10, (unsigned long )(& __retres2));
#line 14
  __retres2 = 0;
  {
  __CrestLoad(11, (unsigned long )(& __retres2), (long long )__retres2);
  __CrestReturn(12);
#line 5
  return (__retres2);
  }
}
}
void __globinit_prj_test1(void) 
{ 

  {
  __CrestInit();
}
}
